### ISSUE TITLE
the simple-examples url can Not be accessed, could you help with?

### ISSUE THREAD

**Issue by phenylazide** [KurtzmanLab/SSTMap#104]
I can Not open this website  http://sstmap.org/2017/05/03/simple-examples/. Is it expired ?

**Comment by KurtzmanEtai** [comment]
phenylazide, where is the html link for this.  WIll you send the web page?

**Comment by tkurtzman** [comment]
Phenylazide, where did you find the link for this?  Also, if you have usage questions, please email me: simpleliquid@gmail.com and cc: anthonycruzpr@gmail.com

**Comment by tkurtzman** [comment]
It's here.  The link I found on the website works.  Not sure where you found yours but please send me so we can remove it.

http://sstmap.org/2017/06/03/simple-examples/
