### ISSUE TITLE
when I run test_gist_output.py, there is an unsolved error: test_gist_output.py: error: the following arguments are required: -t/--test_gist_summary, -r/--ref_gist_summary

### ISSUE THREAD

**Issue by lu-lu-xue** [KurtzmanLab/SSTMap#105]
first time, after i run it, one error below appears:
NameError: name 'ArgumentParser' is not defined
i import argparse, and this problem was solved. 

then i run second time, another error shows that:
test_gist_output.py: error: the following arguments are required: -t/--test_gist_summary, -r/--ref_gist_summary

i tried many times and struggled to find corresponding solutions, but nothing worked😞

here i am asking for help to solve this problem. 

looking forward to your reply! Thanks!!!

**Comment by acruzpr** [comment]
Hello,
Sorry that it took so long to answer, but I was not aware of this issue...
Did you download the test suite from dropbox?
