### ISSUE TITLE
  import _sstmap_ext as calc ModuleNotFoundError: No module named '_sstmap_ext'.

### ISSUE THREAD

**Issue by llxuefighting** [KurtzmanLab/SSTMap#106]
besides, when i want to try an example in pycharm, another error says that:
    import _sstmap_ext as calc
ModuleNotFoundError: No module named '_sstmap_ext'.

up to now i have not appropriate solution to it. 
looking forward to your reply! Thanks!!!

**Comment by llxuefighting** [comment]
The problem seems solved.

According to those installation instructions I installed SSTMap successfully. 

However I can't find it in Project interpreter of pycharm. Just I found one solution: use python3 setup.py install instead of "python setup.py install". Now I can see it in Project interpreter. 😀

[I had this problem maybe because I installed python with more than one version. ]

**Comment by tkurtzman** [comment]
Thanks Ilxue.  Somehow missed the notifications from your original posts.  If you have problems in the future and don't receive a response, email me directly: simpleliquid@gmail.com
