### ISSUE TITLE
Error on using Gromacs generated files in run_hsa

### ISSUE THREAD

**Issue by AGGA32** [KurtzmanLab/SSTMap#108]
Hello,

I have trouble using the ### run_hsa command. I generated my topology and trajectory using Gromacs. Upon using this command, I got this error (Please see attached).

In line with this, I would like to ask for assistance on what are the possibles errors whether on the topology file any else. Thank you and have a great day!

![Error (SSTMap)](https://user-images.githubusercontent.com/69192258/108008704-ef978c80-703b-11eb-930e-a39e7c0e57d8.png)

**Comment by wutobias** [comment]
Hi,
for Gromacs topologies you will need the .gro (for the -i argument ) and the .top (for the -p argument) file. Your command should look something like this:
`run_hsa -i testcase.gro -t md100ps.xtc -l ligand.pdb -p params.top -s 0 -f 100 -o testcase`
Also see http://sstmap.org/2017/06/03/simple-examples/ for additional information.

Hope that helps!
Tobias

**Comment by AGGA32** [comment]
Hello!

Thank you for your help. I ran the run_hsa using Gromacs generated files.

I have another question. During my run, there is a **segmentation fault** occurred (Please see attached). I check the entropy calculations folder and the PDB file doesn't have any data inside. Is this a normal occurrence?

Sincerely,
Alexis

![Screenshot from 2021-02-17 09-22-47](https://user-images.githubusercontent.com/69192258/108143219-45cf0300-7102-11eb-8c55-912b7287c103.png)

**Comment by acruzpr** [comment]
Hi Alexis,

There are some things that I could think could cause this behavior.

Did you use constraints or restraints on the structure to avoid rotations
and translations?

The dna.pdb that you provided with the -l option contains a ligand, or a
group of residues of the area that you want to study?

If it is a ligand, is in the binding site?

Because is weird that you have water, and the program is not finding any
clusters.

Could you answer these questions?

Regards,

Anthony

**Comment by AGGA32** [comment]
Hello,

Regarding the constraints issue, I put constraints in the hydrogen bonding since my structure is a 12-bp DNA (PDB: 1BNA). After MD simulation, I corrected the trajectory using the `gmx trjconv` with an option `-pbc cluster`. I did option since I need to analyze the geometric parameters of the DNA structure.

The dna.pdb file is the 1BNA itself. My goal is to get the solvation entropy of DNA structure at any solvent and cosolvent conditions.

I hope the information that I have provided will help you with troubleshooting.

Thank you.

Sincerely,

Alexis

**Comment by wutobias** [comment]
Hi Alexis,

> Regarding the constraints issue, I put constraints in the hydrogen bonding since my structure is a 12-bp DNA (PDB: 1BNA)

with constraints on hydrogen bonding you mean something like distance restraints? If that is the case, your DNA molecule can still rotate and translate in the simulation box, which is not what you want for the HSA calculations. One way to get rid of rotation and translation is to restrain the DNA molecule to a reference conformation during the MD simulation (e.g. from a crystal structure) using positinal restraints.

Tobias

**Comment by VjayMolino** [comment]
Hi Alexis, 

Can you send  a snapshot of your trajectory? Also, does DNA molecule move during the course of your simulation?

Vjay

**Comment by AGGA32** [comment]
> with constraints on hydrogen bonding you mean something like distance restraints?

I checked again my `.mdp` files for MD simulation. I put the bond parameter constraints as `all-bonds`, not hydrogen bonds only. 

This is the structure in the first frame.
![image](https://user-images.githubusercontent.com/69192258/108301810-b565f080-71dd-11eb-9377-74bd6378c08b.png)

These are the structures at the last 10 ns (90 ns to 100 ns)
![image](https://user-images.githubusercontent.com/69192258/108301920-eba37000-71dd-11eb-9f2f-36799db54b1b.png)
![image](https://user-images.githubusercontent.com/69192258/108301975-0675e480-71de-11eb-8c91-2427e6e187f0.png)
![image](https://user-images.githubusercontent.com/69192258/108302015-17265a80-71de-11eb-9179-ecc2e462b686.png)
![image](https://user-images.githubusercontent.com/69192258/108302030-20afc280-71de-11eb-8759-dec5b158b92c.png)
![image](https://user-images.githubusercontent.com/69192258/108302048-2a392a80-71de-11eb-9ace-c7bda431b643.png)
![image](https://user-images.githubusercontent.com/69192258/108302072-34f3bf80-71de-11eb-9342-305ace5bc334.png)
![image](https://user-images.githubusercontent.com/69192258/108302099-3e7d2780-71de-11eb-9f15-6ba44edec287.png)
![image](https://user-images.githubusercontent.com/69192258/108302113-45a43580-71de-11eb-9010-f730d3e83eac.png)

I hope this will help.

**Comment by VjayMolino** [comment]
Hi Alexis, 

Can you post here the DNA with the water box? It is weird that there were no water clusters found.  

How big is your water box and how many water molecules are in there?


Vjay

**Comment by AGGA32** [comment]
Hello,

Attached is my DNA structure with a water box.

For your reference.

![dna_waterbox](https://user-images.githubusercontent.com/69192258/108307880-ad13b280-71e9-11eb-8932-cd834f992222.png)

**Comment by AGGA32** [comment]
> I checked again my .mdp files for MD simulation. I put the bond parameter constraints as all-bonds, not hydrogen bonds only.

For other information regarding the restraints, the positional restraints of DNA structure (Both A and B chains) are already included in the topology file. 

For your reference.

**Comment by acruzpr** [comment]
Hi Alexis,

Normally, when we want to use SSTMap, we will use positional restraints
during the MD's production phase to avoid any translations or rotations.
This behavior can also be achieved using positional restraint on 3 or 4
atoms in an area far from the binding (in the case of a protein) and with a
high b-factor.

Sometimes when your molecule moves a lot, and you use gmx trjconv, your
molecule will be centered, and the box (water + ions) will be moving around
it. This will cause problems because could be occasions where your molecule
will have parts without water, or your box will be diagonal across your
molecule that will make it difficult to calculate the energies and get
accurate water densities.

I think that this is what is happening here because you have water, but you
are not finding any clusters. The other option is that the dna.pdb does not
overlap with your simulation. If this is the case, SSTMap will be looking
in the wrong place to do the analysis.

Could you please make sure that dna.pdb overlaps with your simulation at
all times or at least on the frames you are using for the analysis and that
your water box is not moving around your molecules?

Also, what version of NumPy are you using?

Regards,

Anthony

**Comment by AGGA32** [comment]
Hello,

Thank you for the insight. I think that my DNA structure moves a lot in the water box as I view it using PyMol. I will study more regarding the positional restraint and how to restrict its movement in different solvent conditions.

The version of NumPy is 1.19.2. I used the `sstmap_py36` environment as stated in your installation tutorial.

I let you know if I already accomplish my task in restricting the DNA structure during MD simulation. I'll post my updates as soon as possible for troubleshooting purposes.

Again, I thank you all for helping me. I do all hope for your safety amidst the pandemic.



Sincerely,

Alexis

**Comment by VjayMolino** [comment]
Hi Alexis,

For NumPy, SSTMap needs a version less than or equal to 1.17.5. 

Vjay

**Comment by AGGA32** [comment]
Hello,

I perform an MD simulation again with a position restrain option for DNA.  I run the `run_hsa` again, and I received this error:
![error_hsa](https://user-images.githubusercontent.com/69192258/108968340-9b378100-76bb-11eb-8a41-c9ff5531598a.png)

I tried to run the `run_gist` and I received this:
![output_gist](https://user-images.githubusercontent.com/69192258/108968401-b0141480-76bb-11eb-9344-949a1d5eef9a.png)

I don't know if any errors occur during the `run_hsa` option. I want to check the entropy values of the two options for comparison.

I hope that you can help me with this error. Thank you and take care!



Regards,
Alexis

**Comment by wutobias** [comment]
Hi Alexis,
do you get any output from the HSA calculations? Something like a file `hsa_hsa_summary.txt` and directory `SSTMap_HSA`? I'm asking because I think (not completely sure though) there should be some sort of run time information printed at the end of the run. Something like:

```Total time running run_entropy_scripts: 0.03 seconds
Total time running normalize_site_quantities: 0.00 seconds
Total time running calculate_site_quantities: 2.02 seconds
Total time running write_calculation_summary: 0.00 seconds
Total time running write_data: 0.02 seconds
```
Tobias

**Comment by AGGA32** [comment]
Hello,

I checked the `SSTMap_HSA` folder. There is no `hsa_hsa_summary.txt` file even in the `entropy_output` directory.

For your reference.


Alexis

**Comment by wutobias** [comment]
Are you using the version from conda or the GitHub version?

You could try the following: 
Make a new conda environment 

```
conda env create --name=sstmap_test -f sstmap_env.yml
conda activate sstmap_test
```

The sstma_env.yml is attached. It contains some other packages that are probably not needed, but it works on my end and builds a working conda environment.

Then download the test suite from https://www.dropbox.com/sh/hrijgk8n5z12bgi/AABSigcBf9PN_7-Z26VCCPePa?dl=0
unzip it and do the following:

```
cd sstmap_test_suite/platforms/amber
$ run_hsa -i testcase.prmtop -t md100ps.nc -l ligand.pdb -s 0 -f 100
```

Now check again the `SSTMap_HSA` directory, is there `hsa_hsa_summary.txt` file?

Greetings,

Tobias

[sstmap_env.yml.zip](https://github.com/KurtzmanLab/SSTMap/files/6044858/sstmap_env.yml.zip)

**Comment by AGGA32** [comment]
Hello,

I already generated the `hsa_hsa_summary.txt` file using the `sstmap_test` environment.

Thank you again for your assistance.



Best regards,

Alexis

**Comment by wutobias** [comment]
Hi,

entropy is kcal/mol (already multiplied by T=300 K). See this very nice summary written by @kamran-haider about the output of HSA and GIST analysis:
http://sstmap.org/2017/05/09/undestanding-output/

Regards,
Tobias

**Comment by AGGA32** [comment]
Hello,

Thank you again for all of the assistance. I will close this issue now.

I do hope for your safety amidst the pandemic.

Sincerely,
Alexis

**Comment by AGGA32** [comment]
@wutobias  If I run another simulation at a different temperature (T is not 300 K), will the entropy unit still be at 300 K or the new reference temperature?

**Comment by wutobias** [comment]
As far as I know (maybe @VjayMolino @acruzpr know more?), the entropy output is always computed at T=300 K. If you run at different T, just multiply the entropy output values by T/300

**Comment by AGGA32** [comment]
Hello,

Thank you for your help. I have one last question. When running the `run_gist` command, should the DNA structure have position restraints?

Thank you.

Alexis

**Comment by wutobias** [comment]
Hi,

it is necessary to make sure the solute does not rotate and translate. So yes, some sort of position restraints will be necessary. The methods section in the SSTMap paper should be a good place to start: https://pubs.acs.org/doi/10.1021/acs.jctc.7b00592

Regards,
Tobias

**Comment by AGGA32** [comment]
This is noted. Again, thank you all for your help.

Sincerely,
Alexis
