### ISSUE TITLE
Index error during `run_gist`

### ISSUE THREAD

**Issue by AGGA32** [KurtzmanLab/SSTMap#109]
Hello!

I got this error during the `run_gist` command. The DNA structure is already positioned restrained. I cannot determine my error in this simulation.

Can someone help me? Thank you.

![image](https://user-images.githubusercontent.com/69192258/112086623-85887f00-8bc7-11eb-948d-ef68d0d2572e.png)

**Comment by joezwu** [comment]
Hello! If you don't mind, can you post your input files and give a brief idea of what you may be trying to do?

**Comment by VjayMolino** [comment]
Hi Alexis, what python and NumPy version did you use to compile sstmap?

**Comment by AGGA32** [comment]
> Hello! If you don't mind, can you post your input files and give a brief idea of what you may be trying to do?

I want to check for the solvation entropy of the DNA structure at different solvent conditions. I got this error during this type of concentration. But I can run GIST analysis at other solvent conditions.

Attached is my topology file and the structural file in GROMACS format.


[150mM Salt, 10% Glycol.zip](https://github.com/KurtzmanLab/SSTMap/files/6186897/150mM.Salt.10.Glycol.zip)

**Comment by AGGA32** [comment]
> Hi Alexis, what python and NumPy version did you use to compile sstmap?

The `python` version is 3.6.12 and the `numpy` version is 1.14.0

**Comment by AGGA32** [comment]
For additional info, I can run the GIST analysis at different solvent conditions. As of now, I rerun my simulation at the specific solvent condition.

**Comment by VjayMolino** [comment]
Hi Alexis. Your indexing error lies in this part of the water_analysis.py code.

line 346:
                __vdw.append([parmed_topology_object.atoms[at].sigma,
                            parmed_topology_object.atoms[at].epsilon])
                chg.append(parmed_topology_object.atoms[at].charge)__

Parmed is not finding all the atoms which might have caused the indexing error. Make sure that all the itp files and the topology file are in the same directory. If this doesn't solve the problem, maybe you can try running a short simulation (100ps) and share the files with us so we can take a better look at what's causing the error.

**Comment by wutobias** [comment]
Hi,
the top file you provided is not valid it seems. If you take a look in it, there is effectively no topology information present. That's what causing the indexing error I guess. Look here for an example of a valid topology file: https://manual.gromacs.org/archive/5.0.1/online/top.html

--Tobias

**Comment by AGGA32** [comment]
> the top file you provided is not valid it seems. If you take a look in it, there is effectively no topology information present. That's what causing the indexing error I guess. Look here for an example of a valid topology file: https://manual.gromacs.org/archive/5.0.1/online/top.html
> 

I already tried the suggestion of @VjayMolino to include all the `.itp` and `.top` files at the topology. It still cannot perform GIST analysis. The solvent condition is 150 mM salt with 10% glycol. I can perform `run_gist` in other solvent conditions.

I performed another simulation with a 100 ps MD simulation run. I let you know if the error still persists.

Thank you again for your help.

**Comment by acruzpr** [comment]
Hi Alexis,

Could you share a 100 frame trajectory and all the files you used to run
the analysis (including all itp files sourced in the top file) to try to
reproduce the error and troubleshoot it?

Also, include the mdp you used to prepare the tpr for the production MD.

**Comment by AGGA32** [comment]
Hello,

I already rerun my simulation at 100 ps, and `run_gist` is already done. Thank you for your help.
