### ISSUE TITLE
Running GIST fails with seg fault error

### ISSUE THREAD

**Issue by lumi96** [KurtzmanLab/SSTMap#110]
Hi all, 

I have been trying to run GIST calculations with gromacs trajectories. Running HSA works however when i try to run GIST I get the following error output (this is reproducible in several machines and with the test file provided here too, including those from different md platforms): 
----------------------------------------------------------------------------------------------------------------------------
Grid information:
	GIST grid center: 36.441 47.116 50.693

	GIST grid dimensions: 30 30 30

	GIST grid spacing: 0.500 A^3

Segmentation fault            | 0.0% Done.
----------------------------------------------------------------------------------------------------------------------------
Any recommendations? 

-Fatlum

**Comment by wutobias** [comment]
Hi Fatlum,

could you post the output from `conda env export --no-builds` here? 
Are you using the GitHub version or conda version of SSTMap?

--Tobias

**Comment by lumi96** [comment]
Hi Tobias, 

I am using the GitHub version (I believe). Here is the output of the conda env: 

name: sstmap_py36
channels:
  - omnia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - blosc=1.21.0
  - bzip2=1.0.8
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - gsl=2.2.1
  - hdf5=1.10.4
  - intel-openmp=2020.2
  - ld_impl_linux-64=2.33.1
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libstdcxx-ng=9.1.0
  - lz4-c=1.9.3
  - lzo=2.10
  - mdtraj=1.9.1
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - mock=4.0.3
  - ncurses=6.2
  - numexpr=2.7.3
  - numpy=1.19.2
  - numpy-base=1.19.2
  - openssl=1.1.1j
  - pandas=1.1.3
  - pip=21.0.1
  - pytables=3.6.1
  - python=3.6.13
  - python-dateutil=2.8.1
  - pytz=2021.1
  - readline=8.1
  - scipy=1.5.2
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.35.2
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - cycler==0.10.0
    - kiwisolver==1.3.1
    - matplotlib==2.2.3
    - parmed==3.2.0
    - pyparsing==3.0.0b2
    - sstmap==1.1.4

**Comment by lumi96** [comment]
This solved the problem. Thank you! 

-Fatlum
