### ISSUE TITLE
Inquiry on the .xtc file for solvation thermodynamics calculations

### ISSUE THREAD

**Issue by AGGA32** [KurtzmanLab/SSTMap#111]
Hello,

I want to ask regarding the `.xtc` file for solvation thermodynamics analysis. Is the `.xtc` file must be PBC corrected or not? In Gromacs, the trajectory file must be corrected due to the PBC. This can be done using `gmx trjconv`. Is the SSTMap PBC sensitive or not?

**Comment by acruzpr** [comment]
Hi,

You need to make sure that all molecules are inside the simulation box.

**Comment by AGGA32** [comment]
Hello,

All of my molecules are inside the simulation box. But as I compare the two trajectories (one with PBC corrected and one without), the thermodynamic values are different as I used the `gistpp` tool.

Should I use the trajectory file with PBC correction or without?

I hope you can help me with this matter.

**Comment by acruzpr** [comment]
Hi,
Yes, you should use a trajectory file with PBC corrections.

**Comment by AGGA32** [comment]
Thank you very much.
