### ISSUE TITLE
Possible bugs: calculating probable configs and translational entropy

### ISSUE THREAD

**Issue by qyuan71** [KurtzmanLab/SSTMap#113]
Dear SSTMap developers,

When testing SSTMap I found potential bugs that influence the calculation:
- The return type of _**prob**_  in _sstmap_probable.cpp is **int**, which causes the program to crash. And it can be corrected by using a **void** return type instead.
- In the translational entropy calculation code in **kdhsa102.cpp**, hard coded "10000" was used in line 578, where I think it should be "numvals" instead according to my literature research.

I have created a pull request based on the above two fixes, let me know if any of these is not correct or do not make sense to you.

Best wishes,

Qi

**Comment by Yeonji-Ji** [comment]
Hello, 
Thanks for the opinion.
