### ISSUE TITLE
terminate called when running test_hsa

### ISSUE THREAD

**Issue by leonwehrhan** [KurtzmanLab/SSTMap#115]
I have used SSTMap for GIST calculations which worked fine. However, when I try HSA on my trajectories, as well as when I run the test suite I get terminate called.

When I run
 
`make test_hsa`

I get:

```
Reading trajectory for clustering.
Performing an initial clustering over 10 frames.
Reading trajectory to obtain water molecules for each cluster.
Refining initial cluster positions by considering 100 frames.
Final number of clusters: 25
Total time running generate_clusters: 0.22 seconds
Total time running initialize_site_data: 0.00 seconds
Total time running initialize_hydration_sites: 0.22 seconds
Writing PDB file containing all HSA region water molecules for entropy calculations.
Done.
Writing PDB files for all water molecules in each hydration site.
Done.
Total time running generate_data_for_entropycalcs: 0.11 seconds
Generating expanded cluster water files...
Running entropy calculation from extension module.
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 39) > this->size() (which is 0)
Aborted
make: *** [Makefile:5: test_hsa] Error 134
```
Python 3.6.13
SSTMap 1.1.3

**Comment by shevsea** [comment]
I'm having the same issue. 

`make test_hsa
cd tests/; python test_platforms_hsa.py
Testing: amber
Initializing ...
Obtaining non-bonded parameters for the system ...
Total time running generate_nonbonded_params: 0.10 seconds
Done.
Assigning hydrogen bond types ...
Total time running assign_hb_types: 0.00 seconds
Done.
Total time running __init__: 0.13 seconds
System information:
        Parameter file: /home/shevsea/software/sstmap_test_suite/platforms/amber/testcase.prmtop

        Trajectory: /home/shevsea/software/sstmap_test_suite/platforms/amber/md100ps.nc

        Total Atoms: 3026, Waters: 1001, Solute Atoms: 23

Reading trajectory for clustering.
Performing an initial clustering over 10 frames.
Reading trajectory to obtain water molecules for each cluster.
Refining initial cluster positions by considering 100 frames.
Final number of clusters: 25
Total time running generate_clusters: 0.12 seconds
Total time running initialize_site_data: 0.00 seconds
Total time running initialize_hydration_sites: 0.12 seconds
Writing PDB file containing all HSA region water molecules for entropy calculations.
Done.
Writing PDB files for all water molecules in each hydration site.
Done.
Total time running generate_data_for_entropycalcs: 0.05 seconds
Generating expanded cluster water files...
Running entropy calculation from extension module.
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 39) > this->size() (which is 0)
Aborted
make: *** [Makefile:5: test_hsa] Error 134`

**Comment by Yeonji-Ji** [comment]
Hello, 
Sorry that it took so long to answer, but I was not aware of this issue.
Could you send me the files so that I can figure it out?
