### ISSUE TITLE
Visualize and Interpretation of Results

### ISSUE THREAD

**Issue by debanjansen48** [KurtzmanLab/SSTMap#116]
after running the test issuing make test_quick command it generates following files with a massage "** Documents/SSTMAP-test/sstmap_test_suite/ref_calcs/gist-gO.dx
	Passed!**"

gist-all.out,  gist-dTSorient-dens.dx  gist-gH.dx, gist-dipole-dens.dx   gist-dTSsix-dens.dx,   gist-gO.dx, gist-dipolex-dens.dx  gist-dTStrans-dens.dx   gist-neighbor-norm.dx, gist-dipoley-dens.dx  gist-Esw-dens.dx        gist-order-norm.dx, gist-dipolez-dens.dx  gist-Eww-dens.dx        ptraj.gist

**requesting you kindly help me out to visualize the results..utilyzing chimera or pymol or vmd**

1) 	Total Atoms: 3026, Waters: 1001, Solute Atoms: 23

Reading trajectory for clustering.
Performing an initial clustering over 10 frames.
Reading trajectory to obtain water molecules for each cluster.
Refining initial cluster positions by considering 100 frames.
Final number of clusters: 25
Total time running generate_clusters: 0.15 seconds
Total time running initialize_site_data: 0.00 seconds
Total time running initialize_hydration_sites: 0.15 seconds
Writing PDB file containing all HSA region water molecules for entropy calculations.
Done.
Writing PDB files for all water molecules in each hydration site.
Done.
Total time running generate_data_for_entropycalcs: 0.06 seconds
Generating expanded cluster water files...
Running entropy calculation from extension module.
Total time running run_entropy_scripts: 0.03 seconds
Total time running normalize_site_quantities: 0.00 seconds
Total time running calculate_site_quantities: 2.29 seconds
Total time running write_calculation_summary: 0.00 seconds
Total time running write_data: 0.02 seconds

2)
	Frames: 100, Total Atoms: 3026, Waters: 1001, Solute Atoms: 23

Grid information:
	GIST grid center: 18.030 17.173 17.058

	GIST grid dimensions: 20 20 20

	GIST grid spacing: 0.500 A^3

Total referenced orientational entropy of the grid: dTSorient = -19.65971 kcal/mol, Nf=100
Total referenced translational entropy of the grid: dTStrans =  -9.66241 kcal/mol, Nf=100
Total 6d if all one vox:  -2.35649 kcal/mol
Total t if all one vox:  -0.55820 kcal/mol
Total o if all one vox:  -0.59395 kcal/mol
Total time running calculate_entropy: 0.01 seconds
Total time running calculate_grid_quantities: 2.38 seconds
Writing voxel data ...
Total time running write_data: 0.14 seconds
Summary of main calculations:
Number of frames processed: 100
	Average number of water molecules over the grid: 15
	Total Solute-Water Energy over the grid: -81.356876
	Total Water-Water Energy over the grid: -116.754827

**and the test water field.**

~/Documents/SSTMAP-test/sstmap_test_suite$ make test_water
cd tests/; python test_water_models.py
Testing: tip3p
Initializing ...
Obtaining non-bonded parameters for the system ...
Total time running generate_nonbonded_params: 0.30 seconds
Done.
Assigning hydrogen bond types ...
Total time running assign_hb_types: 0.01 seconds
Done.
Initializing ...
Total time running __init__: 0.45 seconds
System information:
	Parameter file: /home/debanjan/Documents/SSTMAP-test/sstmap_test_suite/water_models/tip3p/tip3p.prmtop

	Trajectory: /home/debanjan/Documents/SSTMAP-test/sstmap_test_suite/water_models/tip3p/md100ps.nc

	Frames: 100, Total Atoms: 7743, Waters: 2581, Solute Atoms: 0

Grid information:
	GIST grid center: 22.506 22.156 21.516

	GIST grid dimensions: 20 20 20

	GIST grid spacing: 0.500 A^3

Total referenced orientational entropy of the grid: dTSorient =  -0.12832 kcal/mol, Nf=100
Total referenced translational entropy of the grid: dTStrans =  -0.15166 kcal/mol, Nf=100
Total 6d if all one vox:  -0.29620 kcal/mol
Total t if all one vox:  -0.00646 kcal/mol
Total o if all one vox:   0.22335 kcal/mol
Total time running calculate_entropy: 0.01 seconds
Total time running calculate_grid_quantities: 3.51 seconds
Writing voxel data ...
Total time running write_data: 0.15 seconds
Summary of main calculations:
**Number of frames processed: 100
	Average number of water molecules over the grid: 10
	Total Solute-Water Energy over the grid: 0.000000
	Total Water-Water Energy over the grid: -105.056113
Generating dx files ...
Total time running generate_dx_files: 0.08 seconds
Testing: tip4p
Initializing ...
Segmentation fault (core dumped)
Makefile:11: recipe for target 'test_water' failed
make: *** [test_water] Error 139**

Thanks

**Comment by Yeonji-Ji** [comment]
Hi, sorry for the late response. I don't think I understood your question exactly... but you can basically visualize dx files using VMD or PyMol easily.
