### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by debanjansen48** [KurtzmanLab/SSTMap#117]
run_hsa -i 43-a.prmtop -t prod_30ns.nc -l 1RS.pdb -s 0 -f 100 -o testcase
Initializing ...
Obtaining non-bonded parameters for the system ...
Total time running generate_nonbonded_params: 2.32 seconds
Done.
Assigning hydrogen bond types ...
Total time running assign_hb_types: 2.99 seconds
Done.
Total time running __init__: 5.97 seconds
Reading trajectory for clustering.
Performing an initial clustering over 10 frames.
Reading trajectory to obtain water molecules for each cluster.
Refining initial cluster positions by considering 100 frames.
Final number of clusters: 0
Total time running generate_clusters: 2.55 seconds
Total time running initialize_site_data: 0.00 seconds
Total time running initialize_hydration_sites: 2.55 seconds
System information:
	Parameter file: /media/debanjan/DS-1TB/GIST/GIST-RUN/43-a.prmtop

	Trajectory: /media/debanjan/DS-1TB/GIST/GIST-RUN/prod_30ns.nc

	Total Atoms: 32417, Waters: 9443, Solute Atoms: 4088

	Number of clusters: 0

Writing PDB file containing all HSA region water molecules for entropy calculations.
Done.
Writing PDB files for all water molecules in each hydration site.
Done.
Total time running generate_data_for_entropycalcs: 0.22 seconds
Generating expanded cluster water files...
Segmentation fault (core dumped)

**Initially i used numpy 1.17 as mentioned in installation guide
after the issue arise i followed #110 closed issue advice and re build it using numpy 1.14 still it showing errors**

**Comment by Yeonji-Ji** [comment]
Hello,
Sorry that it took so long to answer, but I don't understand why it happened.
Could you send me the files so that I can figure it out?

**Comment by debanjansen48** [comment]
Sure sir, today after be in my lab...I will send you all the files.

**Comment by debanjansen48** [comment]
(sstmap) debanjan@debanjan:/media/debanjan/DS-1TB/Project/Amisha/Apo-MD/1FR$ run_hsa -i ../md_100.gro -t ../md_100.xtc -l sele.pdb -p ../topol.top -s 0 -f 100 -o testcase
Initializing ...
Obtaining non-bonded parameters for the system ...
Total time running generate_nonbonded_params: 3.98 seconds
Done.
Assigning hydrogen bond types ...
Total time running assign_hb_types: 0.80 seconds
Done.
Total time running __init__: 7.21 seconds
Reading trajectory for clustering.
Performing an initial clustering over 10 frames.
Reading trajectory to obtain water molecules for each cluster.
Refining initial cluster positions by considering 100 frames.
Final number of clusters: 0
Total time running generate_clusters: 1.22 seconds
Total time running initialize_site_data: 0.00 seconds
Total time running initialize_hydration_sites: 1.22 seconds
System information:
	Parameter file: /media/debanjan/DS-1TB/Project/Amisha/Apo-MD/md_100.gro

	Trajectory: /media/debanjan/DS-1TB/Project/Amisha/Apo-MD/md_100.xtc

	Total Atoms: 33859, Waters: 9582, Solute Atoms: 5113

	Number of clusters: 0

Writing PDB file containing all HSA region water molecules for entropy calculations.
Done.
Writing PDB files for all water molecules in each hydration site.
Done.
Total time running generate_data_for_entropycalcs: 0.05 seconds
Generating expanded cluster water files...
Segmentation fault (core dumped)

**Comment by Yeonji-Ji** [comment]
@debanjansen48 Sorry for the late response. Could you sent the files to fortunate.yj@gmail.com so I can try it using my computer?

**Comment by debanjansen48** [comment]
i shared the files (trajectory, top file, ligand.pdb file, tpr file, itp file etc and output files) long back in given id fortunate.yj@gmail.com. it will be helpful if you guide us to visualize the results using pymol, vmd or chimera or with any other tools for analysis.
