### ISSUE TITLE
testing sstmap with test_sstmap_suite

### ISSUE THREAD

**Issue by kamran-haider** [KurtzmanLab/SSTMap#26]
# sstmap_test_suite
Test systems for SSTMap

Thank you for helping us test SSTMap.   This short guide will step you through the installation and how to run the test cases.   If you don't have any problems, this should take less than half an hour.   If anything does fail, please post here so we can address it. You can let us know of any issues either via email or by raising an issue at this issue tracker.

## Install Anaconda
Follow the instructions at:
http://sstmap.org/2017/05/02/getting-started/
or
https://www.continuum.io/downloads

## Install SSTMap using conda
Note: If you have a previous inatallation of sstmap, make sure to run 'conda remove sstmap' prior to installation.
```
conda config --add channels omnia
conda config --add channels solvationtools
conda install sstmap
```
## Obtain the test suite
This has a number of short trajectories in different MD packages as well as testing scripts.  It is quite large (500Mb).

https://www.dropbox.com/sh/hrijgk8n5z12bgi/AABSigcBf9PN_7-Z26VCCPePa?dl=0

Download the entire directory as a `zip` file and unzip into a new directory, e.g.,
```
mkdir my_tests
cd my_tests
unzip sstmap_test_suite
```
##  Run testing scripts
Make sure you clean up the test suite so that previously stored test results are removed.
```
make clean
```
### Quick Test
This command will run a quick test calculation and will output if the calculated quantities pass the tests against validated outputs.
```
make test_quick
```
### Test different MD platforms
These will test if the SSTMap installation works smoothly when given inputs from different MD packages.
```
make test_hsa
make test_gist
```
### Test different water models
These will test if the SSTMap installation works smoothly when different water models are used in an MD simulation. In the root test suite folder, do the following:
```
make test_water
```
## Test on your own trajectories

Most importantly, please test this on any trajectories you happen to have.   Instructions for running SSTMap for a popular MD packages (Amber, OpenMM, NAMD, CHARMM, DESMOND, Gromacs) can be found at:

http://sstmap.org/2017/05/03/simple-examples/

Any feedback you have on any aspect of this would be much appreciated.  Thanks for your time.

**Comment by jeiros** [comment]
Hi,

I saw your paper on JCTC and would be interested in testing out the software since I run ligand binding simulations with AMBER. Here's a report on my installation experience on a MacOS 10.13.1.

I use conda, these are the commands I issued for the installation:
```bash
conda create -n sstmap python=2.7 -yq
source activate sstmap
conda config --add channels omnia
conda config --add channels solvationtools
conda install -yq sstmap
```
With the environment active, I can confirm everything looks like it's properly installed:
```
# packages in environment at /Users/je714/miniconda3/envs/sstmap:
#
ca-certificates           2017.08.26           ha1e5d58_0
certifi                   2017.11.5        py27hfa9a1c4_0
intel-openmp              2018.0.0             h8158457_8
libcxx                    4.0.1                h579ed51_0
libcxxabi                 4.0.1                hebd6815_0
libedit                   3.1                  hb4e282d_0
libffi                    3.2.1                h475c297_4
libgcc                    4.8.5               hdbeacc1_10
libgfortran               3.0.1                h93005f0_2
mdtraj                    1.5.1                np19py27_0    omnia
mkl                       2018.0.1             hfbd8650_4
ncurses                   6.0                  hd04f020_2
numpy                     1.9.3            py27hb3dd696_3
openssl                   1.0.2n               hdbc3d79_0
pandas                    0.21.1           py27h1cb45b9_0
parmed                    2.7.3                    py27_1    omnia
pip                       9.0.1            py27h1567d89_4
python                    2.7.14              hde5916a_29
python-dateutil           2.6.1            py27hd56c96b_1
pytz                      2017.3           py27h803c07a_0
readline                  7.0                  hc1231fa_4
scipy                     1.0.0            py27h793f721_0
scripttest                1.3                      py27_0    omnia
setuptools                36.5.0           py27h2a45cec_0
six                       1.11.0           py27h7252ba3_1
sqlite                    3.20.1               h7e4c145_2
sstmap                    v1.0                     py27_0    solvationtools
tk                        8.6.7                h35a86e2_3
wheel                     0.30.0           py27h677a027_1
zlib                      1.2.11               hf3cbc9b_2
```
Running `python quick_test.py` gives an error:
```
RuntimeError: module compiled against API version a but this version of numpy is 9
Traceback (most recent call last):
  File "quick_test.py", line 6, in <module>
    from sstmap.grid_water_analysis import GridWaterAnalysis
  File "/Users/je714/miniconda3/envs/sstmap/lib/python2.7/site-packages/sstmap/__init__.py", line 41, in <module>
    from sstmap import site_water_analysis, grid_water_analysis, utils
  File "/Users/je714/miniconda3/envs/sstmap/lib/python2.7/site-packages/sstmap/site_water_analysis.py", line 38, in <module>
    from sstmap.utils import *
  File "/Users/je714/miniconda3/envs/sstmap/lib/python2.7/site-packages/sstmap/utils.py", line 29, in <module>
    import _sstmap_ext as calc
ImportError: numpy.core.multiarray failed to import
```
A `conda install numpy` command fixed the problem by upgrading it from `1.9.3` to `1.13.3` (also my `mdtraj` got updated from `1.5.1` to `1.9.1`) but now it complained about `matplotlib` not being installed:
```
Traceback (most recent call last):
  File "quick_test.py", line 6, in <module>
    from sstmap.grid_water_analysis import GridWaterAnalysis
  File "/Users/je714/miniconda3/envs/sstmap/lib/python2.7/site-packages/sstmap/__init__.py", line 41, in <module>
    from sstmap import site_water_analysis, grid_water_analysis, utils
  File "/Users/je714/miniconda3/envs/sstmap/lib/python2.7/site-packages/sstmap/site_water_analysis.py", line 38, in <module>
    from sstmap.utils import *
  File "/Users/je714/miniconda3/envs/sstmap/lib/python2.7/site-packages/sstmap/utils.py", line 34, in <module>
    import matplotlib as mpl
ImportError: No module named matplotlib
```
I know I can manually install the dependencies until the import errors go away (in fact it did), but you might want to check that your conda recipe is properly specifying all the necessary dependencies for sstmap -- I Haven't really build conda recipes myself so not too sure how they work.
Also, the final output of `python quick_test.py` was:
```
Testing: amber
Initializing ...
Total time running __init__: 1.26 seconds
System information:
	Parameter file: /Users/je714/Downloads/sstmap_test_suite/platforms/amber/testcase.prmtop

	Trajectory: /Users/je714/Downloads/sstmap_test_suite/platforms/amber/md100ps.nc

	Periodic Box: Orthorhombic

	Frames: 100, Total Atoms: 3026, Waters: 1001, Solute Atoms: 23

Grid information:
	GIST grid center: 18.030 17.173 17.058

	GIST grid dimensions: 48 48 48

	GIST grid spacing: 0.500 A^3

Progress |====================| 100.0% Done.
Total referenced orientational entropy of the grid: dTSorient = -132.12159 kcal/mol, Nf=100
watcount in vol = 42865
watcount in subvol = 37915
Total referenced translational entropy of the grid: dTStrans = -98.71101 kcal/mol, Nf=100
Total 6d if all one vox:  -1.40032 kcal/mol
Total t if all one vox:  -0.26035 kcal/mol
Total o if all one vox:  -0.12461 kcal/mol
Total time running calculate_entropy: 0.09 seconds
Total time running calculate_grid_quantities: 22.01 seconds
Writing voxel data ...
Total time running write_data: 2.38 seconds
Traceback (most recent call last):
  File "quick_test.py", line 41, in <module>
    run_all_gist_tests(data_dir + "/testcase_gist_data.txt", "ref_gist_output.dat")
  File "/Users/je714/miniconda3/envs/sstmap/lib/python2.7/site-packages/sstmap/testing/test_gist_output.py", line 204, in run_all_gist_tests
    raise IOError("%s and/or %s directory not found, please provide correct path." % (test_dir, ref_dir))
IOError: amber/gist_output/testcase_gist_data.txt and/or ref_gist_output.dat directory not found, please provide correct path.
```
It looks like some file that should be there is not?

Thanks for making this open source, hope my report can help you out 😄

**Comment by kamran-haider** [comment]
Hi @jeiros 

Thanks so much for trying out the test suite and providing details on how your installation worked. Surprisingly, some of the import errors occur only when working from conda environments (not from default conda installation). It is definitely good to know and I will fix the conda recipe so that the automatic resolution of dependencies goes smoothly. I think some of the reference files in the test suite changed recently leading to file IO errors.  We will update the test suite as well. Thanks again and I will update the thread as soon as I fix these issues.

**Comment by jeiros** [comment]
Yes, I presume the imports errors happen because I have miniconda installed, which is just python and nothing else. The default full conda installation has many pre-installed scientific python packages, so I guess creating a new environment from it would work (have not tested that).

**Comment by kamran-haider** [comment]
Hi @jeiros 

Just wanted to update you that I have attempted to fix this problem. I have tested on my own by replicating the commands you pasted above and didn't get the import issues. Please feel free to test again and see if it works for you.

Regarding the other issue of a missing file in the test suite, that is also fixed. The `sstmap_test_suite` is fully up-to-date now. In the updated test suite, we have simplified the testing a little bit. Now once you download the test suite from the Dropbox link, you can simply unzip and cd to the test suite folder and run make commands to run tests, e.g:
```
make test_quick
make test_hsa
make test_gist
make test_water
```

I have updated the original (topmost) post with this information and you can also find it at:

https://github.com/KurtzmanLab/sstmap_test_suite/blob/master/README.md
