### ISSUE TITLE
Mac Installation - wget

### ISSUE THREAD

**Issue by tkurtzman** [KurtzmanLab/SSTMap#27]
Wget is not part of the default mac installation.

**Comment by tkurtzman** [comment]
curl -O https://repo.continuum.io/archive/Anaconda2-4.3.1-MacOSX-x86_64.sh

seems to work

**Comment by kamran-haider** [comment]
Thanks. Will edit the install page accordingly.

**Comment by kamran-haider** [comment]
oops, closed by mistake. Let's keep it open for now
