### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by tkurtzman** [KurtzmanLab/SSTMap#33]
For the tutorial:

$run_hsa -i testcase.prmtop -t testcase.nc -l ligand.pdb -s 0 -n 100 -o "testcase"

$run_gist -i testcase.prmtop -t testcase.nc -l ligand.pdb -s 0 -n 100 -d 20.0 20.0 20.0 -o "testcase"

change testcase.prmtop  to italics  _parameterfilename.prmtop_

change "ligand.pdb" to italics _ligandfilename.pdb_

"testcase" to _outputfilename_
"testcase.nc" _trajectoryfilename_

**Comment by kamran-haider** [comment]
For both readme.md and tutorials on sstmap.org, I have specific examples for each platform (only Amber example in readme.md with pointer to other examples), so we may not need a generic command.
