### ISSUE TITLE
Install instruction: Installation from source install the wrong version

### ISSUE THREAD

**Issue by acruzpr** [KurtzmanLab/SSTMap#69]
Hi:
Currently, the instructions to install from source doesn't specify the version to check out in order to get the same files available in the release download.

I made a pull request with the changes to fix that in the README.md but also need to be fixed on the website.

**Comment by kamran-haider** [comment]
Thanks so much. I will merge on Monday after returning from vacation.

**Comment by acruzpr** [comment]
Sure no problem!



Sent from my Samsung Galaxy smartphone.


-------- Original message --------
