### ISSUE TITLE
Add energetic breakdown statistics to run_gist

### ISSUE THREAD

**Issue by gosldorf** [KurtzmanLab/SSTMap#96]
In the run_gist output it would be good to include the breakdown the energy statistics further such that there is data for Esw_Elec, Esw_LJ, Eww_Elec, Eww_LJ. These values are available in the run_hsa summary file, but not run_gist.

**Comment by wutobias** [comment]
Hi Steven!
At https://github.com/wutobias/SSTMap/tree/v1.1_dev/sstmap is a version which calculates the breakdown "on the fly" during the pairwise-distance calculation within the C extension (it decreases the overhead generated by the energy breakdown). I've implemented it only for HSA so far, but never got to the point where I could do it for GIST as well. It should not be very difficult. If it is ok for you guys, I could try to do the implementation for GIST, too.

**Comment by gosldorf** [comment]
Hi Tobias,

That would be great! Feel free to write and ask for help if needed!

--Steve

**Comment by wutobias** [comment]
I've just started the pull request into your master branch.

I've tested all new features and functionalities, but I would be happy if you could do some additional testing in your lab. I had to rearrange some of the data structures in the gist class (especially the self.voxeldata attribute and the calculate_grid_quantities method), maybe one of you can check if I didn't mess up anything.
